name: gas_user_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  fluttertoast: ^8.2.12
  get_storage: ^2.1.1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  google_maps_flutter: ^2.12.2
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  lottie: ^3.3.1
  shimmer: ^3.0.0
  geolocator: ^14.0.1
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  share_plus: ^11.0.0
  carousel_slider: ^5.1.1
  badges: ^3.1.2
  data_connection_checker_tv: ^0.3.5-nullsafety
  device_preview: ^1.2.0
  pinput: ^5.0.1
  flutter_rating_bar: ^4.0.1
  qr_flutter: ^4.1.0
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.1
  geocoding: ^4.0.0
  file_picker: ^10.3.3
  image_cropper: ^11.0.0
  open_filex: ^4.7.0
  mime: ^2.0.0
  app_set_id: ^1.3.0
  world_flags: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localization: ^0.3.2
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_gen: ^5.10.0
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/
    - assets/icons/
    - assets/images/
    # - .env
    - assets/animations/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-VariableFont_wght.ttf
        - asset: fonts/Manrope-Bold.ttf
        - asset: fonts/Manrope-ExtraBold.ttf
        - asset: fonts/Manrope-ExtraLight.ttf
        - asset: fonts/Manrope-Light.ttf
        - asset: fonts/Manrope-Medium.ttf
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-SemiBold.ttf
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Bold.ttf
        - asset: fonts/Cairo-ExtraBold.ttf
        - asset: fonts/Cairo-ExtraLight.ttf
        - asset: fonts/Cairo-Light.ttf
        - asset: fonts/Cairo-Medium.ttf
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-SemiBold.ttf
        - asset: fonts/Cairo-Black.ttf

flutter_gen:
  output: lib/presentation/util/resources/
  integrations:
    flutter_svg: true
    lottie: true
    image: true